// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab5FAQ.Models;

#nullable disable

namespace lab5FAQ.Migrations
{
    [DbContext(typeof(FaqContext))]
    [Migration("20220216142422_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lab5FAQ.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            CategoryName = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("lab5FAQ.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A css framework for creating responsive web apps for multiple screens.",
                            CategoryId = "gen",
                            Question = "What is BootStrap?",
                            TopicId = "boot"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "A general purpose object-oriented language that uses a concise, Java-like syntax",
                            CategoryId = "gen",
                            Question = "What is C#?",
                            TopicId = "c#"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "A general purpose scripting language that executes in a browser",
                            CategoryId = "gen",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "For things.",
                            CategoryId = "hist",
                            Question = "Why is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Bootstrap is your friend.",
                            CategoryId = "hist",
                            Question = "Who is BootStrap?",
                            TopicId = "boot"
                        });
                });

            modelBuilder.Entity("lab5FAQ.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "js",
                            TopicName = "JavaScript"
                        },
                        new
                        {
                            TopicId = "boot",
                            TopicName = "BootStrap"
                        },
                        new
                        {
                            TopicId = "c#",
                            TopicName = "C#"
                        });
                });

            modelBuilder.Entity("lab5FAQ.Models.FAQ", b =>
                {
                    b.HasOne("lab5FAQ.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab5FAQ.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
